name: AdventOfCode
options:
  bundleIdPrefix: cz.lukashromadnik
targets:
  01 Secret Entrance:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/01 Secret Entrance]
  02 Gift Shop:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/02 Gift Shop]
  03 Lobby:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/03 Lobby]
  04 Printing Department:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/04 Printing Department]
    dependencies:
      - package: Core
  05 Cafeteria:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/05 Cafeteria]
  06 Trash Compactor:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/06 Trash Compactor]
    dependencies:
      - package: Core
  07 Laboratories:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/07 Laboratories]
    dependencies:
      - package: Core
  08 Playground:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/08 Playground]
    dependencies:
      - package: Core
  09 Movie Theater:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/09 Movie Theater]
  10 Factory:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/10 Factory]
  11 Reactor:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/11 Reactor]
  12 Christmas Tree Farm:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/12 Christmas Tree Farm]
packages:
  Collections:
    url: https://github.com/apple/swift-collections
    from: 1.1.0
  Algorithms:
    url: https://github.com/apple/swift-algorithms
    from: 1.2.0
  Core:
    path: ../Core