name: AdventOfCode
options:
  bundleIdPrefix: cz.lukashromadnik
targets:
  Core:
    type: framework
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/Core]
  SecretEntrance:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/01 Secret Entrance]
  GiftShop:
    type: tool
    platform: macOS
    deploymentTarget: "15.0"
    sources: [Sources/02 Gift Shop]
packages:
  Collections:
    url: https://github.com/apple/swift-collections
    from: 1.1.0
  Algorithms:
    url: https://github.com/apple/swift-algorithms
    from: 1.2.0