name: AdventOfCode
options:
  bundleIdPrefix: cz.lukashromadnik
targets:
  NotQuiteLisp:
    type: tool
    platform: macOS
    deploymentTarget: "14.0"
    sources: [Sources/NotQuiteLisp]
  WrappingPaper:
    type: tool
    platform: macOS
    deploymentTarget: "14.0"
    sources: [Sources/WrappingPaper]
  PresentsDelivery:
    type: tool
    platform: macOS
    deploymentTarget: "14.0"
    sources: [Sources/PresentsDelivery]
  AdventCoins:
    type: tool
    platform: macOS
    deploymentTarget: "14.0"
    sources: [Sources/AdventCoins]
  NiceString:
    type: tool
    platform: macOS
    deploymentTarget: "14.0"
    sources: [Sources/NiceString]
packages:
  Collections:
    url: https://github.com/apple/swift-collections
    from: 1.0.5